# Generated by Django 4.1.6 on 2023-05-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Price',
            field=models.IntegerField(max_length=100),
        ),
    ]
